# Generated by Django 2.1.2 on 2018-11-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='key',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='numberCorrect',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='numberTotal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentNumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
