# Generated by Django 2.1.2 on 2018-11-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20181106_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='key',
        ),
        migrations.RemoveField(
            model_name='student',
            name='numberCorrect',
        ),
        migrations.RemoveField(
            model_name='student',
            name='numberTotal',
        ),
        migrations.AlterField(
            model_name='student',
            name='studentNumber',
            field=models.CharField(default='12345', max_length=20),
        ),
    ]
