# Generated by Django 2.1.1 on 2018-09-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20180910_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='account',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='account',
            name='classroom',
        ),
        migrations.AddField(
            model_name='account',
            name='classroom',
            field=models.ManyToManyField(to='teacher.Classroom'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
