# Generated by Django 2.1.1 on 2018-10-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20181006_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='key',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
