# Generated by Django 2.1.1 on 2018-10-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20180920_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ('name', 'key')},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='id',
        ),
        migrations.AddField(
            model_name='classroom',
            name='key',
            field=models.CharField(default='Classroom', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstName',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastName',
            field=models.CharField(default='', max_length=40),
        ),
    ]
