# Generated by Django 2.1.1 on 2018-10-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20181007_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='key',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
