# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-27 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180927_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='score',
        ),
    ]
