# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-27 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_room_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
